// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ParticlesBg from "@/components/ParticlesBg"

// // const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import "./globals.css"
import ParticlesBg from "@/components/ParticlesBg"
import ScrollProgress from "../components/ScrollProgress"
import CursorGlow from "../components/CursorGlow"
import { ThemeProvider } from "next-themes"

export default function RootLayout({ children }: { children: React.ReactNode }) {

return (
<html lang="en">

<body>

<ScrollProgress/>
<CursorGlow/>
<ParticlesBg/>
<ThemeProvider attribute="class">

{children}

</ThemeProvider>

</body>

</html>
)

}

